# Generated by Django 5.2.11 on 2026-02-25 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Heuristic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "heuristic",
                "verbose_name_plural": "heuristics",
            },
        ),
        migrations.CreateModel(
            name="HeuristicGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "heuristics",
                    models.ManyToManyField(
                        related_name="groups",
                        to="heuristics.heuristic",
                        verbose_name="heuristics",
                    ),
                ),
            ],
            options={
                "verbose_name": "heuristic group",
                "verbose_name_plural": "heuristic groups",
            },
        ),
        migrations.CreateModel(
            name="HeuristicEvaluation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("critical", "Critical"),
                        ],
                        verbose_name="level",
                    ),
                ),
                ("problems", models.TextField(blank=True, verbose_name="problems")),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="recommendations"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "heuristic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="heuristics.heuristic",
                        verbose_name="heuristic",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heuristic_evaluations",
                        to="analysis.page",
                        verbose_name="page",
                    ),
                ),
            ],
            options={
                "verbose_name": "heuristic evaluation",
                "verbose_name_plural": "heuristic evaluations",
                "unique_together": {("page", "heuristic")},
            },
        ),
    ]
