# Generated by Django 5.2.11 on 2026-02-25 03:06

from django.db import migrations, models

import heuriva.apps.analysis.fields
import heuriva.apps.analysis.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "short_id",
                    models.CharField(
                        default=heuriva.apps.analysis.models.generate_short_id,
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="short ID",
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="sequence number"
                    ),
                ),
                ("score", models.CharField(verbose_name="score")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("crawling", "Crawling"),
                            ("crawl_completed", "Crawl Completed"),
                            ("analyzing", "Analyzing Heuristics"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="celery task id",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="error message"
                    ),
                ),
                (
                    "executive_summary",
                    models.TextField(
                        blank=True, null=True, verbose_name="executive summary"
                    ),
                ),
                (
                    "priorities",
                    models.JSONField(blank=True, null=True, verbose_name="priorities"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "analysis",
                "verbose_name_plural": "analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("path", models.CharField(verbose_name="path")),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=heuriva.apps.analysis.models.upload_to_media,
                        verbose_name="screenshot",
                    ),
                ),
                (
                    "html_content",
                    heuriva.apps.analysis.fields.ZstdCompressedTextField(
                        blank=True, null=True, verbose_name="HTML content"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "page",
                "verbose_name_plural": "pages",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "short_id",
                    models.CharField(
                        default=heuriva.apps.analysis.models.generate_short_id,
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="short ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="name")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "homepage_screenshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=heuriva.apps.analysis.models.upload_to_media,
                        verbose_name="homepage screenshot",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
    ]
