# Generated by Django 5.2.11 on 2026-02-25 00:03

from django.db import migrations, models

import heuriva.apps.analysis.models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_analysis_sequence_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="short_id",
            field=models.CharField(
                default=heuriva.apps.analysis.models.generate_short_id,
                editable=False,
                max_length=12,
                unique=True,
                verbose_name="short ID",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="short_id",
            field=models.CharField(
                default=heuriva.apps.analysis.models.generate_short_id,
                editable=False,
                max_length=12,
                unique=True,
                verbose_name="short ID",
            ),
        ),
    ]
